version: "2"

linters:
  default: standard
  enable:
    - goconst
    - misspell
    - unconvert
    - unparam
    - copyloopvar
    - makezero
    - wastedassign
  disable:
    - errcheck

formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - gofumpt
    - swaggo
