version: "2"

linters:
  default: standard
  enable:
    - copyloopvar
    - goconst
    - makezero
    - misspell
    - modernize
    - unconvert
    - unparam
    - wastedassign

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - swaggo
