FROM registry.access.redhat.com/ubi7/ubi:7.7-214 AS base

# Install make libraries for build environment
# Then clean caches
RUN yum --disableplugin=subscription-manager install -y \
        make-3.82-24.el7 \
    && yum --disableplugin=subscription-manager clean all \
    && rm -rf /var/cache/yum /var/lib/yum/yumdb

FROM base
RUN echo test
