FROM debian:12.10 AS first-image

RUN mkdir -p /tmp/testdir \
    && echo "hello" > /tmp/testdir/file.txt \
    && touch -d '2000-01-01' /tmp/testdir \
    && touch -d '2000-01-01' /tmp/testdir/file.txt

RUN stat /tmp/testdir \
    && stat /tmp/testdir/file.txt

# assert that snapshot did not touch atime. we can't use diffoci for that,
# as buildkit does not snapshot atime, they are only present during build.
RUN [ $(stat -c %X /tmp/testdir) -eq $(date -d '2000-01-01' +%s) ] \
    && [ $(stat -c %X /tmp/testdir) -eq $(date -d '2000-01-01' +%s) ]

FROM debian:12.10 AS second-image

COPY --from=first-image /tmp/testdir /tmp/testdir

RUN stat /tmp/testdir \
    && stat /tmp/testdir/file.txt
