FROM ubuntu:24.04@sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b

# Fails on main@1d2bff5 before #3393:
# When we COPY files into an existing folder
# kaniko will not only copy the permissions from the context
# onto the newly created files and folders. But will
# also modify the permissions on the top level folder, even if it pre-exists.
# This is aberrant behaviour, other build-tools persist the permissions.
# In this specific case this leads to build-failure as sticky bit is lost on /tmp
COPY ./ tmp
RUN apt-get update \
    && apt-get install -y curl \
    && rm -rf /var/lib/apt/lists/*
