FROM busybox:latest

# mz473: in kaniko v1.26.4, due to a regression in our CopyDir,
# When running kaniko with KANIKO_DIR=/kaniko2 in order to relocate the binary,
# The binary would simply get deleted instead.
# Verify here that relocation indeed works.
RUN if ls -l /proc/1/exe | grep -q '/kaniko/executor'; then \
        [ ! -d /kaniko ]; \
        [ -f /kaniko2/executor ]; \
    else \
        echo "PID1 is not Kaniko, skipping check"; \
    fi
