FROM alpine as base_stage
RUN echo base_stage
RUN touch meow.txt

FROM base_stage as bug_stage
RUN echo bug_stage
RUN touch purr.txt


FROM bug_stage as final_stage
RUN echo final_stage
RUN touch mew.txt
