FROM debian:12.10 AS first-image

RUN mkdir -p /tmp/testdir \
    && echo "hello" > /tmp/testdir/file.txt \
    && touch -d '2000-01-01' /tmp/testdir \
    && touch -d '2000-01-01' /tmp/testdir/file.txt

RUN stat /tmp/testdir \
    && stat /tmp/testdir/file.txt

# assert that snapshot did not touch atime. we can't use diffoci for that,
# as buildkit does not snapshot atime, they are only present during build.
# starting with docker v29 buildkit snapshotter will modifity atime on snapshot.
RUN if ls -l /proc/1/exe | grep -q '/kaniko/executor'; then \
        if [ $(stat -c %X /tmp/testdir) -ne $(date -d '2000-01-01' +%s) ]; then \
            echo "FAIL: atime changed on /tmp/testdir"; \
            exit 1; \
        fi; \
        if [ $(stat -c %X /tmp/testdir/file.txt) -ne $(date -d '2000-01-01' +%s) ]; then \
            echo "FAIL: atime changed /tmp/testdir/file.txt"; \
            exit 1; \
        fi; \
    else \
        echo "PID1 is not Kaniko, skipping check"; \
    fi

FROM debian:12.10 AS second-image

COPY --from=first-image /tmp/testdir /tmp/testdir

RUN stat /tmp/testdir \
    && stat /tmp/testdir/file.txt
