FROM alpine
RUN mkdir /app && echo "normal" > /app/data.txt && \
    if ls -l /proc/1/exe | grep -q '/kaniko/executor'; then \
        touch /kaniko-extra-file && \
        mkdir /kaniko-extra-dir && touch /kaniko-extra-dir/child.txt; \
    fi
