dockerfile: |-
  FROM debian:12.10 AS base
  RUN install

  FROM base AS build
  RUN compile

  FROM base AS final
  COPY --from=build output output

  FROM final AS test
  RUN test
tests:
  - args: ["--target=final", "--destination=registry"]
    # TODO: clean after "base" stage is unnecesary
    plan: |-
      FROM debian:12.10 AS base
      RUN install
      SAVE STAGE /kaniko/stages/0
      CLEAN

      FROM base (/kaniko/stages/0) AS build
      RUN compile
      SAVE FILES [output] /kaniko/deps/1
      CLEAN

      FROM base (/kaniko/stages/0) AS final
      COPY --from=build output output
      PUSH [registry]
  - args: ["--target=final", "--target=build", "--destination=registry"]
    # TODO: clean after "base" stage is unnecesary
    plan: |-
      FROM debian:12.10 AS base
      RUN install
      SAVE STAGE /kaniko/stages/0
      CLEAN

      FROM base (/kaniko/stages/0) AS build
      RUN compile
      SAVE FILES [output] /kaniko/deps/1
      CLEAN

      FROM base (/kaniko/stages/0) AS final
      COPY --from=build output output
      PUSH [registry]
  # The first target is what we push
  - args: ["--target=final", "--target=test", "--destination=registry"]
    # TODO: clean after "base" stage is unnecesary
    # TODO: saving the "final" stage is unnecessary
    # TODO: clean after "final" stage is unnecesary
    plan: |-
      FROM debian:12.10 AS base
      RUN install
      SAVE STAGE /kaniko/stages/0
      CLEAN

      FROM base (/kaniko/stages/0) AS build
      RUN compile
      SAVE FILES [output] /kaniko/deps/1
      CLEAN

      FROM base (/kaniko/stages/0) AS final
      COPY --from=build output output
      PUSH [registry]
      SAVE STAGE /kaniko/stages/2
      CLEAN

      FROM final (/kaniko/stages/2) AS test
      RUN test
