/*
Copyright 2026 OSS Container Tools

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package creds

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/docker/cli/cli/config"
	"github.com/docker/cli/cli/config/configfile"
	"github.com/docker/cli/cli/config/types"
	"github.com/google/go-containerregistry/pkg/authn"
	"github.com/google/go-containerregistry/pkg/name"
)

// PathScopedKeychain implements authn.Keychain the same way authn.DefaultKeychain does,
// but additionally tries every intermediate repository path between the exact resource
// and the bare registry host, so a credential configured for a namespace such as:
//
//   - "registry.example.com/org-a" is found when authenticating against
//   - "registry.example.com/org-a/project/image"
//     not just against an exact match or the bare registry host.
//
// Repository-path candidates, including an exact repository match,
// are looked up only in the inline "auths" map (file-based and DOCKER_AUTH_CONFIG-based).
// The bare registry host uses ConfigFile.GetAuthConfig, preserving the existing credsStore
// and credHelpers behavior without ever passing a repository path to a credential helper.
var PathScopedKeychain authn.Keychain = pathScopedKeychain{}

type pathScopedKeychain struct{}

// Resolve implements authn.Keychain.
func (pathScopedKeychain) Resolve(target authn.Resource) (authn.Authenticator, error) {
	cf, err := loadDockerConfig()
	if err != nil {
		return nil, err
	}
	if cf == nil {
		// Docker CLI can resolve DOCKER_AUTH_CONFIG without an auth file.
		// Use an empty ConfigFile so its host-level credential-store lookup retains
		// that behavior while scoped candidates use envAuths below.
		cf = configfile.New("")
	}

	// Credential helpers are registry-scoped
	// Repository-path candidates resolve against a copy with the helpers stripped,
	// so they only ever see inline auths entries and DOCKER_AUTH_CONFIG
	scoped := *cf
	scoped.CredentialsStore = ""
	scoped.CredentialHelpers = nil

	keys := authKeyLookupOrder(target)
	for i, key := range keys {
		if key == name.DefaultRegistry {
			key = authn.DefaultAuthKey
		}

		lookup := &scoped
		if i == 0 || i == len(keys)-1 {
			// Only the bare registry host goes through Docker's full credsStore/credHelpers-aware lookup
			lookup = cf
		}
		cfg, err := lookup.GetAuthConfig(key)
		if err != nil {
			return nil, err
		}
		// ConfigFile.LoadFromReader sets ServerAddress even for an empty auths entry.
		// It is metadata, not a credential, so exclude it from the empty-config check for every lookup candidate.
		cfg.ServerAddress = ""
		if cfg != (types.AuthConfig{}) {
			return authn.FromConfig(authn.AuthConfig{
				Username:      cfg.Username,
				Password:      cfg.Password,
				Auth:          cfg.Auth,
				IdentityToken: cfg.IdentityToken,
				RegistryToken: cfg.RegistryToken,
			}), nil
		}
	}

	return authn.Anonymous, nil
}

// authKeyLookupOrder returns the auth-file lookup keys for target, most specific first:
// the exact resource, each intermediate repository path (only when target is repository-aware),
// then the bare registry host.
// Parent paths are generated by dropping whole slash-delimited path segments, never by string-prefix trimming,
// so a credential configured for "registry/org" can never match "registry/org-admin"
func authKeyLookupOrder(target authn.Resource) []string {
	keys := []string{target.String()}

	if repo, ok := target.(name.Repository); ok {
		segments := strings.Split(repo.RepositoryStr(), "/")
		for i := len(segments) - 1; i > 0; i-- {
			keys = append(keys, repo.RegistryStr()+"/"+strings.Join(segments[:i], "/"))
		}
	}

	if host := target.RegistryStr(); keys[len(keys)-1] != host {
		keys = append(keys, host)
	}

	return keys
}

// loadDockerConfig locates and loads the same Docker/Podman auth config file authn.DefaultKeychain would use,
// replicating its file-discovery order:
//
//   - $HOME/.docker/config.json,
//   - else $DOCKER_CONFIG/config.json
//   - else $REGISTRY_AUTH_FILE
//   - else Podman's containers/auth.json under $XDG_RUNTIME_DIR or $XDG_CONFIG_HOME
//
// Returns (nil, nil) if none of those exist, matching DefaultKeychain's fallback to an anonymous result.
func loadDockerConfig() (*configfile.ConfigFile, error) {
	foundDockerConfig := false
	home, err := os.UserHomeDir()
	if err == nil {
		foundDockerConfig = fileExists(filepath.Join(home, ".docker/config.json"))
	}
	if !foundDockerConfig && os.Getenv("DOCKER_CONFIG") != "" {
		foundDockerConfig = fileExists(filepath.Join(os.Getenv("DOCKER_CONFIG"), "config.json"))
	}
	configDir := os.Getenv("XDG_CONFIG_HOME")
	if configDir == "" && home != "" {
		configDir = filepath.Join(home, ".config")
	}
	podmanAuth := filepath.Join(os.Getenv("XDG_RUNTIME_DIR"), "containers/auth.json")
	if (os.Getenv("XDG_RUNTIME_DIR") == "" || !fileExists(podmanAuth)) && configDir != "" {
		podmanAuth = filepath.Join(configDir, "containers/auth.json")
	}

	switch {
	case foundDockerConfig:
		return config.Load(os.Getenv("DOCKER_CONFIG"))

	case fileExists(filepath.Clean(os.Getenv("REGISTRY_AUTH_FILE"))):
		f, err := os.Open(filepath.Clean(os.Getenv("REGISTRY_AUTH_FILE")))
		if err != nil {
			return nil, err
		}
		defer f.Close()
		return config.LoadFromReader(f)

	case fileExists(filepath.Clean(podmanAuth)):
		f, err := os.Open(filepath.Clean(podmanAuth))
		if err != nil {
			return nil, err
		}
		defer f.Close()
		return config.LoadFromReader(f)

	default:
		return nil, nil
	}
}

func fileExists(path string) bool {
	fi, err := os.Stat(path)
	return err == nil && !fi.IsDir()
}
