apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: local-registry
  namespace: kube-system
spec:
  chart: https://github.com/twuni/docker-registry.helm/archive/refs/tags/v2.2.2.tar.gz
  set:
    # Expose the registry server on localhost
    service.type: "LoadBalancer"
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: local-tls-registry
  namespace: kube-system
spec:
  chart: https://github.com/twuni/docker-registry.helm/archive/refs/tags/v2.2.2.tar.gz
  valuesContent: |-
    service:
      type: LoadBalancer
      port: 5001
    tlsSecretName: local-tls-registry-cert
    extraEnvVars:
      - name: REGISTRY_AUTH
        value: token
      - name: REGISTRY_AUTH_TOKEN_REALM
        value: https://localhost:5002/auth
      - name: REGISTRY_AUTH_TOKEN_SERVICE
        value: kaniko-test-registry
      - name: REGISTRY_AUTH_TOKEN_ISSUER
        value: kaniko-test-auth
      - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
        value: /auth/tls.crt
    extraVolumes:
      - name: auth
        secret:
          secretName: local-tls-registry-cert
          items:
            - key: tls.crt
              path: tls.crt
    extraVolumeMounts:
      - name: auth
        mountPath: /auth
        readOnly: true
