apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-test-{{.Name}}
spec:
  template:
    spec:
      hostNetwork: true
      containers:
      - name: kaniko
        image: localhost:5000/executor:latest
        workingDir: /workspace
        args: [ "--context=dir:///workspace",
                "--destination={{.KanikoImage}}"]
        {{- if .CoverageDir}}
        env:
        - name: GOCOVERDIR
          value: /covdata
        {{- end}}
        volumeMounts:
        - name: context
          mountPath: /workspace
        {{- if .CoverageDir}}
        - name: covdata
          mountPath: /covdata
        {{- end}}
      restartPolicy: Never
      volumes:
      - name: context
        hostPath:
          path: {{.Context}}
      {{- if .CoverageDir}}
      - name: covdata
        hostPath:
          path: {{.CoverageDir}}
      {{- end}}
  backoffLimit: 1
