name: Integration tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  tests:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
      COVERAGE_DIR: '${{ github.workspace }}/out/covdata'

    strategy:
      fail-fast: false
      matrix:
        make-target:
          - integration-test-layers
          - integration-test-misc
          - integration-test-run
          - k8s-executor-build-push integration-test-k8s

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@90e01b21170618765a73370fcc3abbd1684a7793 # v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26.5'

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 # v5.3.0
        with:
          version: 29.5.2

      - run: make install-diffoci k3s-setup
      - run: make ${{ matrix.make-target }}

      - name: Convert and upload coverage
        run: |
          go tool covdata textfmt -i out/covdata -o coverage.txt

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.txt
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
