name: Integration tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:
  tests:
    name: bisect-${{ matrix.group }}
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
      COVERAGE_DIR: '${{ github.workspace }}/out/covdata'
      TEST_PARALLELISM: '1'
      TEST_DOCKERFILE_LIST: '${{ matrix.list }}'

    strategy:
      fail-fast: false
      matrix:
        include:
          - group: "all"
            list: "Dockerfile_test_issue_mz332,Dockerfile_test_add_chown_intermediate_dirs,Dockerfile_test_multistage_args_issue_1911,Dockerfile_test_add_url_with_arg,Dockerfile_test_issue_mz282,Dockerfile_test_copy,Dockerfile_test_issue_cg188,Dockerfile_test_issue_mz622,Dockerfile_test_copy_symlink,Dockerfile_test_issue_3393,Dockerfile_test_volume_4,Dockerfile_test_cache_copy,Dockerfile_test_whitelist,Dockerfile_test_user_nonexisting,Dockerfile_test_issue_mz863,Dockerfile_test_issue_mz731,Dockerfile_test_copy_reproducible,Dockerfile_test_issue_mz320,Dockerfile_test_extraction,Dockerfile_test_issue_mz798,Dockerfile_test_run_new,Dockerfile_test_arg_from_single_quotes,Dockerfile_test_issue_mz247,Dockerfile_test_issue_mz276,Dockerfile_test_cache_copy_oci,Dockerfile_test_issue_mz896,Dockerfile_test_issue_mz595,Dockerfile_test_parent_dir_perms,Dockerfile_test_issue_mz334,Dockerfile_test_root,Dockerfile_test_issue_3429,Dockerfile_test_maintainer,Dockerfile_test_daemons,Dockerfile_test_dockerignore,Dockerfile_test_issue_1039,Dockerfile_test_expose,Dockerfile_test_copy_same_file_many_times,Dockerfile_test_issue_mz155,Dockerfile_test_complex_substitution"
          - group: "g0"
            list: "Dockerfile_test_issue_mz332,Dockerfile_test_copy_symlink,Dockerfile_test_copy_reproducible,Dockerfile_test_cache_copy_oci,Dockerfile_test_daemons,Dockerfile_test_complex_substitution"
          - group: "g1"
            list: "Dockerfile_test_add_chown_intermediate_dirs,Dockerfile_test_issue_3393,Dockerfile_test_issue_mz320,Dockerfile_test_issue_mz896,Dockerfile_test_dockerignore,Dockerfile_test_complex_substitution"
          - group: "g2"
            list: "Dockerfile_test_multistage_args_issue_1911,Dockerfile_test_volume_4,Dockerfile_test_extraction,Dockerfile_test_issue_mz595,Dockerfile_test_issue_1039,Dockerfile_test_complex_substitution"
          - group: "g3"
            list: "Dockerfile_test_add_url_with_arg,Dockerfile_test_cache_copy,Dockerfile_test_issue_mz798,Dockerfile_test_parent_dir_perms,Dockerfile_test_expose,Dockerfile_test_complex_substitution"
          - group: "g4"
            list: "Dockerfile_test_issue_mz282,Dockerfile_test_whitelist,Dockerfile_test_run_new,Dockerfile_test_issue_mz334,Dockerfile_test_copy_same_file_many_times,Dockerfile_test_complex_substitution"
          - group: "g5"
            list: "Dockerfile_test_copy,Dockerfile_test_user_nonexisting,Dockerfile_test_arg_from_single_quotes,Dockerfile_test_root,Dockerfile_test_issue_mz155,Dockerfile_test_complex_substitution"
          - group: "g6"
            list: "Dockerfile_test_issue_cg188,Dockerfile_test_issue_mz863,Dockerfile_test_issue_mz247,Dockerfile_test_issue_3429,Dockerfile_test_complex_substitution"
          - group: "g7"
            list: "Dockerfile_test_issue_mz622,Dockerfile_test_issue_mz731,Dockerfile_test_issue_mz276,Dockerfile_test_maintainer,Dockerfile_test_complex_substitution"

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@90e01b21170618765a73370fcc3abbd1684a7793 # v5
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26.5'

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: docker/setup-docker-action@6d7cfa65f60a9dda7b46e5513fa982536f3c9877 # v5.3.0
        with:
          version: 29.5.2

      - run: make install-diffoci k3s-setup
      - run: make integration-test-run

      - name: Convert and upload coverage
        run: |
          go tool covdata textfmt -i out/covdata -o coverage.txt

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          files: coverage.txt
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
